services:
    AppCommand:
        class: Akeneo\Apps\Infrastructure\Cli\AppCommand
        arguments:
            - '@akeneo_app.application.handler.create_app'
            - '@akeneo_app.application.handler.fetch_apps'
            - '@akeneo_app.application.handler.regenerate_app_secret'
        tags:
            - { name: 'console.command' }

    DeleteAppCommand:
        class: Akeneo\Apps\Infrastructure\Cli\DeleteAppCommand
        arguments:
            - '@akeneo_app.application.handler.delete_app'
        tags:
            - { name: 'console.command' }

    Akeneo\Apps\Infrastructure\Cli\UpdateAuditDataCommand:
        class: Akeneo\Apps\Infrastructure\Cli\UpdateAuditDataCommand
        arguments:
            - '@akeneo_app.application.audit.service.update_product_event_count'
        tags:
            - { name: 'console.command' }
